### ISSUE TITLE
seeds dont really work properly

### ISSUE THREAD

**Issue by arceuss** [b3spectacled/modern-beta#3]
![image](https://user-images.githubusercontent.com/28229451/93264623-a083bd80-f764-11ea-8ad9-93cb708a7b48.png)
title screen seed at same coords

**Comment by arceuss** [comment]
lol i got the x coordinate wrong but its still wrong
![image](https://user-images.githubusercontent.com/28229451/93265651-28b69280-f766-11ea-8692-1adddfdc52d8.png)

**Comment by b3spectacled** [comment]
This should be expected.  Two things:
  * The data pack is constrained by the modern terrain gen system.  It can sometimes reproduce famous landmarks like gargamel and Glacier (see bullet two) but with most seeds, the terrain will just be different.  The old Neo-Beta customized preset has the same limitations (and produces much of the same terrain).
  * Much of the world is just ocean (my decision).  You can attempt to shift biomes around by changing the 'seed' field under 'biome-source' to see if you can get a land biome in this location, but I've checked the panorama seed using the Neo-Beta preset in 1.12 (my baseline for terrain) and the terrain is different there as well.

**Comment by arceuss** [comment]
huh

**Comment by b3spectacled** [comment]
Try this out: http://www.mediafire.com/file/f8qzxwaeytu8hr3/file

This does reproduce the title screen landmark.  This is a Plains-only overworld, just for demonstration.  Since height variation and base height is coded on a per-biome basis, I had to adjust those values for the Plains biome just to produce this specific landmark.  Unfortunately a limitation of the current terrain gen system.

![pano_comparison](https://user-images.githubusercontent.com/68445563/93272311-0d4d8680-f76a-11ea-80fa-65aa9bbe3543.png)

**Comment by vinnyg0621** [comment]
same. seeds never change for me either

**Comment by b3spectacled** [comment]
> 
> 
> same. seeds never change for me either

You're going to have to change the fields in the overworld.json file, as noted in the PMC project description.

**Comment by vinnyg0621** [comment]
thanks so much, it worked for me!
